# App configuration

parameters:
    env(MAILER_USER): '' #fallback MAILER_USER if the env var is not set.
    mailer_user: '%env(resolve:MAILER_USER)%'

# TODO: Move to fos_user.yaml
# see https://symfony.com/doc/master/bundles/FOSUserBundle/index.html#step-4-configure-your-application-s-security-yml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    service:
        mailer: fos_user.mailer.twig_swift # fixes templating service requirement: https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2692#issuecomment-363431743

# TODO: Move to twig.yaml
twig:
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']

# TODO: Move to stof_doctrine_extensions.yaml
stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            blameable: true
            softdeleteable: true

# TODO: Move to services.yaml
services:
    Sg\DatatablesBundle\Response\DatatableResponse: '@sg_datatables.response'

    # TODO: this doesn't work here - it only works if this is placed inside services.yaml
    App\Router\Router:
        decorates: 'router'
        arguments: ['@App\Router\Router.inner']