# TODO: define aliased services explicitly, see: http://symfony.com/doc/current/bundles/best_practices.html#services

services:
#    _defaults:
#        autowire: true
#        autoconfigure: false
#        public: false
#        bind:
#            $askUseDatatable: '%extended_generator.ask_use_datatable%'
#            $useDatatableDefault: '%extended_generator.use_datatable_default%'


#    K3ssen\GeneratorBundle\Command\EntityQuestion\TraitsQuestion: ~

    K3ssen\ExtendedGeneratorBundle\:
        autowire: true
        autoconfigure: true
        public: false
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests}'
        bind:
            $projectDir: '%kernel.project_dir%'


    K3ssen\ExtendedGeneratorBundle\Generator\CrudGenerateOptions:
        parent: 'K3ssen\GeneratorBundle\Generator\CrudGenerateOptions'
        autowire: true
        autoconfigure: false
        public: false
        bind:
            $askUseDatatable: '%extended_generator.ask_use_datatable%'
            $useDatatableDefault: '%extended_generator.use_datatable_default%'
